### ISSUE TITLE
Caching system

### ISSUE THREAD

**Issue by arcturus** [mozilla-magnet/magnet-metadata-service#17]
To speed up analysis we could add a caching system, there is a branch now adding this, but it's a bit obsolete.

**Comment by wilsonpage** [comment]
Do you think we could just use nginx for this? 😛 

Might just be a few lines. Although if not dynamic, we may not be able to honour the cache headers returned from the source.

**Comment by arcturus** [comment]
Actually, I think that honoring the cache headers is the most important part.

Is the only way developers setting up beacons will have to handle the refresh of their creations.

**Comment by samgiles** [comment]
We could use Varnish if we don't use batching - we could even use it with a Fastly trial for London demo

**Comment by arcturus** [comment]
In my mind I had this idea of not having to use any http cache. But a custom cache that stores the result of the parsing.

Something like redis, with key the url and content the result of the parsing, taking into account that you can use records with ttl.

What do you think @samgiles ?
