### ISSUE TITLE
Deploy latest version to tengam.org

### ISSUE THREAD

**Issue by wilsonpage** [mozilla-magnet/magnet-metadata-service#21]
@arcturus @samgiles I don't have box credentials yet.

**Comment by samgiles** [comment]
@wilsonpage send me or @arcturus your public key via email then :).

**Comment by wilsonpage** [comment]
Done, I think :) Launched as follows:
1. `sudo su metadataservice`
2. `pm2 stop app`
3. `git fetch origin && git rebase origin/master`
4. `pm2 start index.js --name magnet-metadata-service`
