### ISSUE TITLE
Objects should have a 'type' property

### ISSUE THREAD

**Issue by wilsonpage** [mozilla-magnet/magnet-metadata-service#4]
In order to start composing tiles for specific pages/apps/content-types the service should pass back a `type` property. It was discussed yesterday that this should likely start with the OpenGraph types and then extend into more specific types in order to help surface actions (eg. 'Follow this person').

OpenGraph types:
- `music`
  - `music.song`
  - `music.album`
  - `music.playlist`
  - `music.radio_station`
- `video`
  - `video.movie`
  - `video.episode`
  - `video.tv_show`
- `article`
- `book`
- `profile`
- `website` (no `og:` metadata)

We can see how a lot of our use-cases fall into one of the OG categories, but in order to surface specific functionality/visuals, we will need to 'extend' one of these types (eg. `profile.twitter`).

**Comment by wilsonpage** [comment]
On the front-end I will render everything as `website` type, until the metadata service starts to include a `type` property.

**Comment by wilsonpage** [comment]
More info here: https://ogp.me/

**Comment by wilsonpage** [comment]
Handy online OG tool: https://developers.facebook.com/tools/debug/og/object/

**Comment by samgiles** [comment]
Closed by #9
