### ISSUE TITLE
No receving any icon for twitter.com/wilsonpage

### ISSUE THREAD

**Issue by wilsonpage** [mozilla-magnet/magnet-metadata-service#5]

**Comment by arcturus** [comment]
Looking at it!

**Comment by arcturus** [comment]
Ok, twitter is adding a link with rel 'shortcut icon' and we are looking just for icon.

We can add this, it's also pretty common, but my question is, if the twitter parser detects that we have a twitter profile, should overwrite the icon field with the user avatar?

@wilsonpage @samgiles thoughts?

**Comment by wilsonpage** [comment]
Hmmmm good question. Personally I think we should keep the twitter icon as the main icon and then use additional image asset within the detailed tile view.

**Comment by wilsonpage** [comment]
My reasoning for this is that when you are using the 'grid' view to quickly scan what's around you, the Twitter logo informs you it's Twitter related content, the title below will give you more detail about the type of twitter content.

A user provided avatar would be less informative here and doesn't distinguish, Twitter from a blog for example.

**Comment by arcturus** [comment]
Sounds good, the icon of an url is what you specify with html standards.

If that url represents a view that we know how draw, extra information (as larger images) should come in the extra metadata fields.
