### ISSUE TITLE
'Malformed' word appears in the tile for the description

### ISSUE THREAD

**Issue by isabelrios** [mozilla-magnet/magnet-metadata-service#50]
This is the original url: https://github.com/mozilla-magnet
Short: goo.gl/XF5Hye

And this is an screenshot:
![screenshot_2016-07-28-14-12-45](https://cloud.githubusercontent.com/assets/1897507/17056940/3c894be0-5017-11e6-9c13-40537457a628.png)

This is what the service returns:
[ { url: 'https://github.com/mozilla-magnet',
    title: 'Project Magnet',
    description: 'malformed',
    icons:
     [ [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object] ],
    icon: 'https://github.com/apple-touch-icon-180x180.png',
    image: 'https://avatars1.githubusercontent.com/u/17905978?v=3&s=280',
    og_data:
     { image: 'https://avatars1.githubusercontent.com/u/17905978?v=3&s=280',
       site_name: 'GitHub',
       type: 'profile',
       title: 'Project Magnet',
       url: 'https://github.com/mozilla-magnet',
       description: 'malformed',
       profile: [Object] },
    unadaptedUrl: 'https://github.com/mozilla-magnet',
    displayUrl: 'https://github.com/mozilla-magnet',
    id: 'https://github.com/mozilla-magnet',
    originalUrl: 'https://github.com/mozilla-magnet',
    maxAge: 30000 } ]

**Comment by wilsonpage** [comment]
This is no longer an issue.
